### PR TITLE
Add the first version of the Friendship model

### LINKED ISSUE #1: Create a model for the friendship
- [x] Add into the corresponding models the associations to have a first version of friendship.

### LINKED ISSUE #10: May 29, 2020 | Code-Review : The Poodles
Nice wor team. One thing I realized is about the user experience. If you can disable the link to send a friend request and don't make it disappear. That would be nice

### LINKED ISSUE #11: Peer to peer code review by Team 65 the Labradors
Hello Oscar and Carlos :wave: :service_dog: 

Good job so far with your Friendship V1 milestone, you almost finish so keep up the good work! we suggested Oscar a couple of changes and these were they:

1. Remove the logic from the views, no if-else statements should exist, instead always prefer to use helpers and partials to render the HTML elements you have in the conditionals.
2. Style your "Invite To Friendship" link to look like a button because it's requested in the pathwright so we strongly recommend to have it.

That's it! :raised_hands: 

Happy coding! :rocket:

### PR DESCRIPTION
**Pull request by Flakster**
In this PR we:
- Create the friendship model and the associations with the existing models.
- Implement the requirements for friendship functionality:
  - Send friendship invitations to other users either from the list of users and from the user's profile page
  - See pending invitations in the user's profile
  - Be able of accept and reject pending invitations

This closes #1, #10, #11

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
# Changes required  ♻️ 

### Hi team!  🌟

**Very nice work on this Milestone 5: Friendships v1, however, the following issues need to be fixed before moving on ⬇️** 



#### Milestone 5: Friendships v1

* [x] User model `has_many :friendships`  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
screenshot
* [x] User model `has_many :inverted_friendships, class_name: "Friendship", foreign_key: "friend_id"` from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
screenshot 
* [x] Friendship model `belongs_to :user`  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
screenshot
* [x] Friendship model `belongs_to :friend, class_name: "User"` from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/)
screenshot 


This article can help you : [Friendships in Active Record](https://smartfunnycool.com/friendships-in-activerecord/.)


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by AlfredoElizarraras** [comment]
Hello @Anna-Myzukina :wave: 
Thanks for your feedback. :pray:
After reading the tutorial, we think the major difference is the name of the associations, the friend can be senders and the inverse friends can be receivers. :thinking: 
We took the hint just as a suggestion and even though we didn't use it, we think our approach is good enough at least for the first version of the friendship association due basically it works as it is supposed to work. :raised_hands:

**Comment by uryelah** [comment]
Hello **Carlos Santamaría Bernal & Alfredo Gómez Elizarrarás**, I'm Sarah your last reviewer for this PR 👩‍🚀 

Good implementing the suggestions from the last review. I agree that what you have is enough for the version one of the friendships milestone.

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**


---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by Flakster** [comment]
Thanks for your feedback :wave: @uryelah

**Pull request merged**
